nelmio_api_doc:
    documentation:
        info:
            title: MGP
            description: This is an awesome contact app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security: 
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags: ['Authentication']
                    summary: 'User login'
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            example: user@example.com
                                        password:
                                            type: string
                                            example: Password123!
                    responses:
                        '200':
                            description: 'Successful login'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                        '401':
                            description: 'Invalid credentials'
                    
    areas:
        path_patterns:
            - ^/api(?!/doc$)

