nelmio_cors:
    defaults:
        allow_origin: []
        allow_credentials: true
        allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
        expose_headers: ["Content-Length", "Content-Type"]
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        max_age: 3600
    paths:
        "^/api":
            allow_origin: ["http://localhost:5173"]
            allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
            expose_headers: ["Content-Length", "Content-Type"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            allow_credentials: true
            max_age: 3600
