services:
  api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MAILER_DSN: smtp://mailhog:1025
      MAILER_DEFAULT_FROM: no-reply@example.test
      FRONT_RESET_BASE_URL: http://localhost:3000/reset-password
    depends_on:
      - database
      - mailhog
    command: sh -c "php -S 0.0.0.0:8000 -t public"
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mgp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mgp}
      POSTGRES_USER: ${POSTGRES_USER:-mgp}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-mgp}",
          "-U",
          "${POSTGRES_USER:-mgp}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  ###< doctrine/doctrine-bundle ###
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  front:
    build:
      context: ../front
    working_dir: /app
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api
    volumes:
      - ../front:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
